### ISSUE TITLE
Cannot find custom modules

### ISSUE THREAD

**Issue by Bugiboop** [JeffWalton-PSC/eRezLife#1]
Hello there! I work for Ringling College of Art + Design, and we're trying to incorporate this code for use on our campus with some tweaking. We were recommended this repo from somebody in Student Life. 
However, I'm noticing two missing modules that I can't seem to find anywhere--which makes me believe they were custom-made for this script and otherwise unavailable: "powercampus" and "local_db".
Is there any chance we could get you to include those modules in either a separate repo, or here in this one (assuming there isn't super-sensitive information in those modules)? 
I'd like to try to avoid the process of attempting to reverse engineer it if at all possible.

Thanks a bunch! :)

**Comment by JeffWalton-PSC** [comment]
The local_db and powercampus packages are here: https://github.com/JeffWalton-PSC/library
You will have to modify them for your purposes.

Let me know if you have other questions.

Good luck,
Jeff

**Comment by Bugiboop** [comment]
Oh, excellent! Thank you very much.
